general:
  output_dir: outputs/finetune_score
  overwrite_output_dir: false
  logging_dir: logs
  report_to: wandb
  cache_dir: null
  max_ckpts_to_keep: 3

training:
  deepspeed_config_path: configs/finetune/deepspeed.json
  gradient_accumulation_steps: 4
  mixed_precision: "no"
  seed: 42
  pretrained_model_name_or_path: openai/clip-vit-large-patch14
  gradient_checkpointing: true
  train_batch_size: 8
  validation_batch_size: 4
  max_train_steps: 2000
  num_train_epochs: 10
  validate_steps: 100
  save_steps: 100 # ${training.validate_steps}
  max_batches_to_generate: 1
  enable_xformers_memory_efficient_attention: false
  num_workers: 0
  continue_from_checkpoint: true
  deepspeed: null
  eval_on_start_train: true

dataset:
  dataset_name: data/datasets/PickaPic_reward.ds
  dataset_config_name: null
  image_column_name: good_image
  bad_image_column_name: bad_image
  caption_column_name: text
  max_examples: null
  from_disk: true
  validation_split_name: test

optimizer:
  learning_rate: 1e-6
  scale_lr: false
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-8
  max_grad_norm: 1.0

lr_scheduler:
  type: constant_with_warmup
  lr_warmup_steps: 250

hf:
  push_to_hub: true
  hub_model_id: null

debug:
  activate: false
  port: 5900

hydra:
  run:
    dir: .

slurm:
  job_name: ft
  partition: killable
  time_limit: 20
  n_processes: 4
