general:
  output_dir: outputs/finetune_sd
  overwrite_output_dir: false
  logging_dir: logs
  report_to: wandb
  cache_dir: null
  max_ckpts_to_keep: 3

training:
  deepspeed_config_path: configs/finetune/deepspeed.json
  gradient_accumulation_steps: 4
  mixed_precision: "no"
  seed: 42
  pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
  prediction_type: epsilon
  gradient_checkpointing: true
  train_batch_size: 2
  validation_batch_size: 4
  resolution: 512
  max_train_steps: 2000
  num_train_epochs: 10
  use_ema: false
  validate_steps: 100
  save_steps: 100 # ${training.validate_steps}
  max_batches_to_generate: 1
  classifier_free_ratio: 0.1
  enable_xformers_memory_efficient_attention: false
  eval_clip_id: openai/clip-vit-large-patch14
  n_eval_steps: 25
  gs: 7
  num_workers: 3
  train_unet: true
  train_text_encoder: true
  train_vae: false
  use_pixel_loss: false
  continue_from_checkpoint: true
  add_face_loss: false
  deepspeed: null
  eval_on_start_train: true
  take_clip_score_on_eval: false

dataset:
  dataset_name: yuvalkirstain/PickaPic-ft-ranked
  dataset_config_name: null
  image_column_name: image
  caption_column_name: text
  max_examples: null

optimizer:
  learning_rate: 1e-6
  scale_lr: false
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1e-2
  adam_epsilon: 1e-8
  max_grad_norm: 1.0

lr_scheduler:
  type: constant_with_warmup
  lr_warmup_steps: 250

hf:
  push_to_hub: true
  hub_model_id: null

debug:
  activate: false
  port: 5900

hydra:
  run:
    dir: .

slurm:
  job_name: ft
  partition: killable
  time_limit: 20
  n_processes: 4
